import {
    mdiAccessPoint,
    mdiAccessPointNetwork,
    mdiAccount,
    mdiAccountGroup,
    mdiAccountGroupOutline,
    mdiAccountOutline,
    mdiAirConditioner,
    mdiAirHumidifier,
    mdiAirHumidifierOff,
    mdiAirPurifier,
    mdiAirPurifierOff,
    mdiAlarm,
    mdiAlarmBell,
    mdiAlarmLight,
    mdiAlarmLightOutline,
    mdiAlarmOff,
    mdiAlarmSnooze,
    mdiAlert,
    mdiAlertBox,
    mdiAlertBoxOutline,
    mdiAlertCircle,
    mdiAlertCircleOutline,
    mdiAlertDecagram,
    mdiAlertDecagramOutline,
    mdiAlertOctagon,
    mdiAlertOctagonOutline,
    mdiAlertOutline,
    mdiArrowCollapse,
    mdiArrowCollapseAll,
    mdiArrowDown,
    mdiArrowDownBold,
    mdiArrowDownBoldCircle,
    mdiArrowExpand,
    mdiArrowExpandAll,
    mdiArrowLeft,
    mdiArrowLeftBold,
    mdiArrowLeftBoldCircle,
    mdiArrowRight,
    mdiArrowRightBold,
    mdiArrowRightBoldCircle,
    mdiArrowUp,
    mdiArrowUpBold,
    mdiArrowUpBoldCircle,
    mdiBackupRestore,
    mdiBattery,
    mdiBattery10,
    mdiBattery20,
    mdiBattery30,
    mdiBattery40,
    mdiBattery50,
    mdiBattery60,
    mdiBattery70,
    mdiBattery80,
    mdiBattery90,
    mdiBatteryAlert,
    mdiBatteryAlertVariant,
    mdiBatteryCharging,
    mdiBatteryCharging10,
    mdiBatteryCharging100,
    mdiBatteryCharging20,
    mdiBatteryCharging30,
    mdiBatteryCharging40,
    mdiBatteryCharging50,
    mdiBatteryCharging60,
    mdiBatteryCharging70,
    mdiBatteryCharging80,
    mdiBatteryCharging90,
    mdiBatteryMinus,
    mdiBatteryOutline,
    mdiBatteryPlus,
    mdiBatterySync,
    mdiBatteryUnknown,
    mdiBell,
    mdiBellMinus,
    mdiBellMinusOutline,
    mdiBellOff,
    mdiBellOffOutline,
    mdiBellOutline,
    mdiBellPlus,
    mdiBellPlusOutline,
    mdiBellRing,
    mdiBellRingOutline,
    mdiBlinds,
    mdiBlindsHorizontal,
    mdiBlindsHorizontalClosed,
    mdiBlindsOpen,
    mdiBlindsVertical,
    mdiBlindsVerticalClosed,
    mdiBluetooth,
    mdiBluetoothConnect,
    mdiBluetoothOff,
    mdiBluetoothSettings,
    mdiBrightness4,
    mdiBrightness5,
    mdiBrightness6,
    mdiBrightness7,
    mdiBrightnessAuto,
    mdiBrightnessPercent,
    mdiCalendar,
    mdiCalendarAlert,
    mdiCalendarBlank,
    mdiCalendarBlankOutline,
    mdiCalendarCheck,
    mdiCalendarClock,
    mdiCalendarMonth,
    mdiCalendarToday,
    mdiCalendarWeek,
    mdiCamera,
    mdiCameraOff,
    mdiCameraOffOutline,
    mdiCameraOutline,
    mdiCameraSwitch,
    mdiCameraSwitchOutline,
    mdiCameraWireless,
    mdiCameraWirelessOutline,
    mdiCarBattery,
    mdiCarBrakeAlert,
    mdiCarBrakeHold,
    mdiCarCoolantLevel,
    mdiCarCruiseControl,
    mdiCarDoor,
    mdiCarDoorLock,
    mdiCarDoorLockOpen,
    mdiCarElectric,
    mdiCarElectricOutline,
    mdiCarLightDimmed,
    mdiCarLightHigh,
    mdiCarParkingLights,
    mdiCarSpeedLimiter,
    mdiCarWash,
    mdiCarWindshield,
    mdiCarWindshieldOutline,
    mdiCast,
    mdiCastConnected,
    mdiCastOff,
    mdiCctv,
    mdiCeilingFan,
    mdiCeilingLight,
    mdiCeilingLightMultiple,
    mdiCeilingLightOutline,
    mdiChartAreaspline,
    mdiChartBar,
    mdiChartLine,
    mdiChartLineVariant,
    mdiCheck,
    mdiCheckBold,
    mdiCheckboxBlank,
    mdiCheckboxBlankOutline,
    mdiCheckboxIntermediate,
    mdiCheckboxIntermediateVariant,
    mdiCheckboxMarked,
    mdiCheckboxMarkedOutline,
    mdiChevronDown,
    mdiChevronLeft,
    mdiChevronRight,
    mdiChevronUp,
    mdiClock,
    mdiClockAlert,
    mdiClockAlertOutline,
    mdiClockCheck,
    mdiClockCheckOutline,
    mdiClockOutline,
    mdiClockTimeFour,
    mdiClockTimeSeven,
    mdiClockTimeTen,
    mdiClockTimeTwelve,
    mdiClose,
    mdiCloseBox,
    mdiCloseBoxOutline,
    mdiCloseCircle,
    mdiCloseCircleOutline,
    mdiCodeJson,
    mdiCoffin,
    mdiContentSave,
    mdiContentSavePlusOutline,
    mdiCursorDefault,
    mdiCursorMove,
    mdiCursorPointer,
    mdiCurtains,
    mdiCurtainsClosed,
    mdiDeleteOutline,
    mdiDesk,
    mdiDeskLamp,
    mdiDipSwitch,
    mdiDoor,
    mdiDoorClosed,
    mdiDoorClosedLock,
    mdiDoorOpen,
    mdiDoorSliding,
    mdiDoorSlidingOpen,
    mdiDoorbell,
    mdiDoorbellVideo,
    mdiDotsGrid,
    mdiDotsHorizontal,
    mdiDotsVertical,
    mdiEvPlugCcs1,
    mdiEvPlugCcs2,
    mdiEvPlugChademo,
    mdiEvPlugType1,
    mdiEvPlugType2,
    mdiEvStation,
    mdiEye,
    mdiEyeOff,
    mdiEyeOffOutline,
    mdiEyeOutline,
    mdiFan,
    mdiFanOff,
    mdiFanSpeed1,
    mdiFanSpeed2,
    mdiFanSpeed3,
    mdiFastForward,
    mdiFileExportOutline,
    mdiFileImageOutline,
    mdiFileImportOutline,
    mdiFilePdfBox,
    mdiFire,
    mdiFireOff,
    mdiFlash,
    mdiFlashAlert,
    mdiFlashAlertOutline,
    mdiFlashOff,
    mdiFlashlight,
    mdiFlashlightOff,
    mdiFloorLamp,
    mdiFloorLampOutline,
    mdiFolderOpenOutline,
    mdiFolderZipOutline,
    mdiGarage,
    mdiGarageAlert,
    mdiGarageAlertVariant,
    mdiGarageOpen,
    mdiGarageVariant,
    mdiGarageVariantLock,
    mdiGasCylinder,
    mdiGasStation,
    mdiGate,
    mdiGateOpen,
    mdiGestureDoubleTap,
    mdiGestureSwipeDown,
    mdiGestureSwipeLeft,
    mdiGestureSwipeRight,
    mdiGestureSwipeUp,
    mdiGestureTap,
    mdiGestureTapHold,
    mdiGestureTwoDoubleTap,
    mdiGestureTwoTap,
    mdiHandWave,
    mdiHeatPump,
    mdiHeatWave,
    mdiHelp,
    mdiHelpCircle,
    mdiHelpCircleOutline,
    mdiHome,
    mdiHomeAccount,
    mdiHomeAlert,
    mdiHomeAlertOutline,
    mdiHomeAnalytics,
    mdiHomeAssistant,
    mdiHomeAutomation,
    mdiHomeCity,
    mdiHomeExportOutline,
    mdiHomeFlood,
    mdiHomeFloor1,
    mdiHomeFloor2,
    mdiHomeFloor3,
    mdiHomeHeart,
    mdiHomeImportOutline,
    mdiHomeLightbulb,
    mdiHomeLightbulbOutline,
    mdiHomeLightningBolt,
    mdiHomeLightningBoltOutline,
    mdiHomeMinus,
    mdiHomeMinusOutline,
    mdiHomeOutline,
    mdiHomePlus,
    mdiHomePlusOutline,
    mdiHvac,
    mdiInformation,
    mdiInformationOutline,
    mdiInformationSlabBox,
    mdiInformationSlabCircle,
    mdiInformationVariant,
    mdiInformationVariantBox,
    mdiInformationVariantCircle,
    mdiKey,
    mdiKeyAlert,
    mdiKeyAlertOutline,
    mdiKeyOutline,
    mdiKeyVariant,
    mdiKeyWireless,
    mdiLamp,
    mdiLampOutline,
    mdiLan,
    mdiLanConnect,
    mdiLanDisconnect,
    mdiLanPending,
    mdiLedStripVariant,
    mdiLightSwitch,
    mdiLightSwitchOff,
    mdiLightbulb,
    mdiLightbulbAuto,
    mdiLightbulbCfl,
    mdiLightbulbCflOff,
    mdiLightbulbFluorescentTube,
    mdiLightbulbGroup,
    mdiLightbulbGroupOff,
    mdiLightbulbGroupOffOutline,
    mdiLightbulbGroupOutline,
    mdiLightbulbOff,
    mdiLightbulbOffOutline,
    mdiLightbulbOn,
    mdiLightbulbOnOutline,
    mdiLightbulbOutline,
    mdiLightningBolt,
    mdiLightningBoltOutline,
    mdiLink,
    mdiLinkVariant,
    mdiLinkVariantOff,
    mdiLock,
    mdiLockAlert,
    mdiLockAlertOutline,
    mdiLockOpen,
    mdiLockOpenVariant,
    mdiLockOpenVariantOutline,
    mdiLockOutline,
    mdiLockReset,
    mdiMenu,
    mdiMenuOpen,
    mdiMinus,
    mdiMinusCircle,
    mdiMinusCircleOutline,
    mdiMonitor,
    mdiMonitorOff,
    mdiMonitorSpeaker,
    mdiMoonWaningCrescent,
    mdiMotionSensor,
    mdiMotionSensorOff,
    mdiMusic,
    mdiMusicBox,
    mdiMusicBoxOutline,
    mdiMusicCircle,
    mdiMusicCircleOutline,
    mdiMusicNote,
    mdiMusicNoteOff,
    mdiMusicOff,
    mdiOpenInNew,
    mdiOutdoorLamp,
    mdiPalette,
    mdiPaletteOutline,
    mdiPause,
    mdiPhone,
    mdiPhoneAlert,
    mdiPhoneHangup,
    mdiPhoneInTalk,
    mdiPipe,
    mdiPipeLeak,
    mdiPlay,
    mdiPlayPause,
    mdiPlaylistCheck,
    mdiPlaylistMinus,
    mdiPlaylistMusic,
    mdiPlaylistPlay,
    mdiPlaylistPlus,
    mdiPlus,
    mdiPlusCircle,
    mdiPlusCircleOutline,
    mdiPool,
    mdiPower,
    mdiPowerCycle,
    mdiPowerOff,
    mdiPowerOn,
    mdiPowerPlug,
    mdiPowerPlugOff,
    mdiPowerPlugOffOutline,
    mdiPowerPlugOutline,
    mdiPowerSettings,
    mdiPowerSleep,
    mdiPowerSocketEu,
    mdiPowerSocketFr,
    mdiPowerSocketUk,
    mdiPowerSocketUs,
    mdiPowerStandby,
    mdiProgressAlert,
    mdiProgressCheck,
    mdiProgressClock,
    mdiProgressClose,
    mdiProgressDownload,
    mdiProgressStar,
    mdiProgressUpload,
    mdiProgressWrench,
    mdiProjector,
    mdiProjectorScreen,
    mdiRadar,
    mdiRadiator,
    mdiRadiatorDisabled,
    mdiRadiatorOff,
    mdiRemote,
    mdiRemoteOff,
    mdiRemoteTv,
    mdiReplay,
    mdiRestart,
    mdiRewind,
    mdiRocket,
    mdiRocketLaunch,
    mdiRocketLaunchOutline,
    mdiRocketOutline,
    mdiRollerShade,
    mdiRollerShadeClosed,
    mdiRouterNetwork,
    mdiRouterWireless,
    mdiRouterWirelessSettings,
    mdiShield,
    mdiShieldHome,
    mdiShieldHomeOutline,
    mdiShieldLock,
    mdiShieldLockOutline,
    mdiShieldOutline,
    mdiSkipNext,
    mdiSkipPrevious,
    mdiSmokeDetector,
    mdiSmokeDetectorAlert,
    mdiSmokeDetectorOutline,
    mdiSmokeDetectorVariant,
    mdiSmokeDetectorVariantAlert,
    mdiSnowflake,
    mdiSnowflakeThermometer,
    mdiSolarPanel,
    mdiSolarPower,
    mdiSolarPowerVariant,
    mdiSpeaker,
    mdiSpeakerBluetooth,
    mdiSpeakerMultiple,
    mdiSpeakerOff,
    mdiSpeakerWireless,
    mdiSpotlight,
    mdiSpotlightBeam,
    mdiStop,
    mdiStringLights,
    mdiStringLightsOff,
    mdiSunWireless,
    mdiSwitch,
    mdiTelevision,
    mdiTelevisionAmbientLight,
    mdiTelevisionClassic,
    mdiTelevisionOff,
    mdiThemeLightDark,
    mdiThermometer,
    mdiThermometerChevronDown,
    mdiThermometerChevronUp,
    mdiThermometerHigh,
    mdiThermometerLines,
    mdiThermometerLow,
    mdiThermostat,
    mdiTimer,
    mdiTimerOff,
    mdiTimerOutline,
    mdiTimerSand,
    mdiTimerSandEmpty,
    mdiToggleSwitch,
    mdiToggleSwitchOff,
    mdiToggleSwitchVariant,
    mdiToggleSwitchVariantOff,
    mdiTransmissionTower,
    mdiTransmissionTowerExport,
    mdiTransmissionTowerImport,
    mdiVolumeHigh,
    mdiVolumeLow,
    mdiVolumeMedium,
    mdiVolumeMute,
    mdiVolumeOff,
    mdiWater,
    mdiWaterOff,
    mdiWaterOutline,
    mdiWaterPercent,
    mdiWaterPump,
    mdiWaterPumpOff,
    mdiWaterThermometer,
    mdiWaterWell,
    mdiWeatherCloudy,
    mdiWeatherFog,
    mdiWeatherNight,
    mdiWeatherNightPartlyCloudy,
    mdiWeatherPartlyCloudy,
    mdiWeatherPouring,
    mdiWeatherRainy,
    mdiWeatherSnowy,
    mdiWeatherSunny,
    mdiWeatherSunnyAlert,
    mdiWeatherSunset,
    mdiWeatherSunsetDown,
    mdiWeatherSunsetUp,
    mdiWeatherWindy,
    mdiWeatherWindyVariant,
    mdiWebcam,
    mdiWebcamOff,
    mdiWifi,
    mdiWifiOff,
    mdiWifiStrength1,
    mdiWifiStrength2,
    mdiWifiStrength3,
    mdiWifiStrength4,
    mdiWifiStrengthOff,
    mdiWindowClosed,
    mdiWindowClosedVariant,
    mdiWindowOpen,
    mdiWindowShutter,
    mdiWindowShutterAlert,
    mdiWindowShutterOpen,
} from '@mdi/js';

export const MDI_PROJECT_PATHS: Record<string, string> = {
    'mdi:access-point': mdiAccessPoint,
    'mdi:access-point-network': mdiAccessPointNetwork,
    'mdi:account': mdiAccount,
    'mdi:account-group': mdiAccountGroup,
    'mdi:account-group-outline': mdiAccountGroupOutline,
    'mdi:account-outline': mdiAccountOutline,
    'mdi:air-conditioner': mdiAirConditioner,
    'mdi:air-humidifier': mdiAirHumidifier,
    'mdi:air-humidifier-off': mdiAirHumidifierOff,
    'mdi:air-purifier': mdiAirPurifier,
    'mdi:air-purifier-off': mdiAirPurifierOff,
    'mdi:alarm': mdiAlarm,
    'mdi:alarm-bell': mdiAlarmBell,
    'mdi:alarm-light': mdiAlarmLight,
    'mdi:alarm-light-outline': mdiAlarmLightOutline,
    'mdi:alarm-off': mdiAlarmOff,
    'mdi:alarm-snooze': mdiAlarmSnooze,
    'mdi:alert': mdiAlert,
    'mdi:alert-box': mdiAlertBox,
    'mdi:alert-box-outline': mdiAlertBoxOutline,
    'mdi:alert-circle': mdiAlertCircle,
    'mdi:alert-circle-outline': mdiAlertCircleOutline,
    'mdi:alert-decagram': mdiAlertDecagram,
    'mdi:alert-decagram-outline': mdiAlertDecagramOutline,
    'mdi:alert-octagon': mdiAlertOctagon,
    'mdi:alert-octagon-outline': mdiAlertOctagonOutline,
    'mdi:alert-outline': mdiAlertOutline,
    'mdi:arrow-collapse': mdiArrowCollapse,
    'mdi:arrow-collapse-all': mdiArrowCollapseAll,
    'mdi:arrow-down': mdiArrowDown,
    'mdi:arrow-down-bold': mdiArrowDownBold,
    'mdi:arrow-down-bold-circle': mdiArrowDownBoldCircle,
    'mdi:arrow-expand': mdiArrowExpand,
    'mdi:arrow-expand-all': mdiArrowExpandAll,
    'mdi:arrow-left': mdiArrowLeft,
    'mdi:arrow-left-bold': mdiArrowLeftBold,
    'mdi:arrow-left-bold-circle': mdiArrowLeftBoldCircle,
    'mdi:arrow-right': mdiArrowRight,
    'mdi:arrow-right-bold': mdiArrowRightBold,
    'mdi:arrow-right-bold-circle': mdiArrowRightBoldCircle,
    'mdi:arrow-up': mdiArrowUp,
    'mdi:arrow-up-bold': mdiArrowUpBold,
    'mdi:arrow-up-bold-circle': mdiArrowUpBoldCircle,
    'mdi:backup-restore': mdiBackupRestore,
    'mdi:battery': mdiBattery,
    'mdi:battery-10': mdiBattery10,
    'mdi:battery-20': mdiBattery20,
    'mdi:battery-30': mdiBattery30,
    'mdi:battery-40': mdiBattery40,
    'mdi:battery-50': mdiBattery50,
    'mdi:battery-60': mdiBattery60,
    'mdi:battery-70': mdiBattery70,
    'mdi:battery-80': mdiBattery80,
    'mdi:battery-90': mdiBattery90,
    'mdi:battery-alert': mdiBatteryAlert,
    'mdi:battery-alert-variant': mdiBatteryAlertVariant,
    'mdi:battery-charging': mdiBatteryCharging,
    'mdi:battery-charging-10': mdiBatteryCharging10,
    'mdi:battery-charging-100': mdiBatteryCharging100,
    'mdi:battery-charging-20': mdiBatteryCharging20,
    'mdi:battery-charging-30': mdiBatteryCharging30,
    'mdi:battery-charging-40': mdiBatteryCharging40,
    'mdi:battery-charging-50': mdiBatteryCharging50,
    'mdi:battery-charging-60': mdiBatteryCharging60,
    'mdi:battery-charging-70': mdiBatteryCharging70,
    'mdi:battery-charging-80': mdiBatteryCharging80,
    'mdi:battery-charging-90': mdiBatteryCharging90,
    'mdi:battery-minus': mdiBatteryMinus,
    'mdi:battery-outline': mdiBatteryOutline,
    'mdi:battery-plus': mdiBatteryPlus,
    'mdi:battery-sync': mdiBatterySync,
    'mdi:battery-unknown': mdiBatteryUnknown,
    'mdi:bell': mdiBell,
    'mdi:bell-minus': mdiBellMinus,
    'mdi:bell-minus-outline': mdiBellMinusOutline,
    'mdi:bell-off': mdiBellOff,
    'mdi:bell-off-outline': mdiBellOffOutline,
    'mdi:bell-outline': mdiBellOutline,
    'mdi:bell-plus': mdiBellPlus,
    'mdi:bell-plus-outline': mdiBellPlusOutline,
    'mdi:bell-ring': mdiBellRing,
    'mdi:bell-ring-outline': mdiBellRingOutline,
    'mdi:blinds': mdiBlinds,
    'mdi:blinds-horizontal': mdiBlindsHorizontal,
    'mdi:blinds-horizontal-closed': mdiBlindsHorizontalClosed,
    'mdi:blinds-open': mdiBlindsOpen,
    'mdi:blinds-vertical': mdiBlindsVertical,
    'mdi:blinds-vertical-closed': mdiBlindsVerticalClosed,
    'mdi:bluetooth': mdiBluetooth,
    'mdi:bluetooth-connect': mdiBluetoothConnect,
    'mdi:bluetooth-off': mdiBluetoothOff,
    'mdi:bluetooth-settings': mdiBluetoothSettings,
    'mdi:brightness-4': mdiBrightness4,
    'mdi:brightness-5': mdiBrightness5,
    'mdi:brightness-6': mdiBrightness6,
    'mdi:brightness-7': mdiBrightness7,
    'mdi:brightness-auto': mdiBrightnessAuto,
    'mdi:brightness-percent': mdiBrightnessPercent,
    'mdi:calendar': mdiCalendar,
    'mdi:calendar-alert': mdiCalendarAlert,
    'mdi:calendar-blank': mdiCalendarBlank,
    'mdi:calendar-blank-outline': mdiCalendarBlankOutline,
    'mdi:calendar-check': mdiCalendarCheck,
    'mdi:calendar-clock': mdiCalendarClock,
    'mdi:calendar-month': mdiCalendarMonth,
    'mdi:calendar-today': mdiCalendarToday,
    'mdi:calendar-week': mdiCalendarWeek,
    'mdi:camera': mdiCamera,
    'mdi:camera-off': mdiCameraOff,
    'mdi:camera-off-outline': mdiCameraOffOutline,
    'mdi:camera-outline': mdiCameraOutline,
    'mdi:camera-switch': mdiCameraSwitch,
    'mdi:camera-switch-outline': mdiCameraSwitchOutline,
    'mdi:camera-wireless': mdiCameraWireless,
    'mdi:camera-wireless-outline': mdiCameraWirelessOutline,
    'mdi:car-battery': mdiCarBattery,
    'mdi:car-brake-alert': mdiCarBrakeAlert,
    'mdi:car-brake-hold': mdiCarBrakeHold,
    'mdi:car-coolant-level': mdiCarCoolantLevel,
    'mdi:car-cruise-control': mdiCarCruiseControl,
    'mdi:car-door': mdiCarDoor,
    'mdi:car-door-lock': mdiCarDoorLock,
    'mdi:car-door-lock-open': mdiCarDoorLockOpen,
    'mdi:car-electric': mdiCarElectric,
    'mdi:car-electric-outline': mdiCarElectricOutline,
    'mdi:car-light-dimmed': mdiCarLightDimmed,
    'mdi:car-light-high': mdiCarLightHigh,
    'mdi:car-parking-lights': mdiCarParkingLights,
    'mdi:car-speed-limiter': mdiCarSpeedLimiter,
    'mdi:car-wash': mdiCarWash,
    'mdi:car-windshield': mdiCarWindshield,
    'mdi:car-windshield-outline': mdiCarWindshieldOutline,
    'mdi:cast': mdiCast,
    'mdi:cast-connected': mdiCastConnected,
    'mdi:cast-off': mdiCastOff,
    'mdi:cctv': mdiCctv,
    'mdi:ceiling-fan': mdiCeilingFan,
    'mdi:ceiling-light': mdiCeilingLight,
    'mdi:ceiling-light-multiple': mdiCeilingLightMultiple,
    'mdi:ceiling-light-outline': mdiCeilingLightOutline,
    'mdi:chart-areaspline': mdiChartAreaspline,
    'mdi:chart-bar': mdiChartBar,
    'mdi:chart-line': mdiChartLine,
    'mdi:chart-line-variant': mdiChartLineVariant,
    'mdi:check': mdiCheck,
    'mdi:check-bold': mdiCheckBold,
    'mdi:checkbox-blank': mdiCheckboxBlank,
    'mdi:checkbox-blank-outline': mdiCheckboxBlankOutline,
    'mdi:checkbox-intermediate': mdiCheckboxIntermediate,
    'mdi:checkbox-intermediate-variant': mdiCheckboxIntermediateVariant,
    'mdi:checkbox-marked': mdiCheckboxMarked,
    'mdi:checkbox-marked-outline': mdiCheckboxMarkedOutline,
    'mdi:chevron-down': mdiChevronDown,
    'mdi:chevron-left': mdiChevronLeft,
    'mdi:chevron-right': mdiChevronRight,
    'mdi:chevron-up': mdiChevronUp,
    'mdi:clock': mdiClock,
    'mdi:clock-alert': mdiClockAlert,
    'mdi:clock-alert-outline': mdiClockAlertOutline,
    'mdi:clock-check': mdiClockCheck,
    'mdi:clock-check-outline': mdiClockCheckOutline,
    'mdi:clock-outline': mdiClockOutline,
    'mdi:clock-time-four': mdiClockTimeFour,
    'mdi:clock-time-seven': mdiClockTimeSeven,
    'mdi:clock-time-ten': mdiClockTimeTen,
    'mdi:clock-time-twelve': mdiClockTimeTwelve,
    'mdi:close': mdiClose,
    'mdi:close-box': mdiCloseBox,
    'mdi:close-box-outline': mdiCloseBoxOutline,
    'mdi:close-circle': mdiCloseCircle,
    'mdi:close-circle-outline': mdiCloseCircleOutline,
    'mdi:code-json': mdiCodeJson,
    'mdi:coffin': mdiCoffin,
    'mdi:content-save': mdiContentSave,
    'mdi:content-save-plus-outline': mdiContentSavePlusOutline,
    'mdi:cursor-default': mdiCursorDefault,
    'mdi:cursor-move': mdiCursorMove,
    'mdi:cursor-pointer': mdiCursorPointer,
    'mdi:curtains': mdiCurtains,
    'mdi:curtains-closed': mdiCurtainsClosed,
    'mdi:delete-outline': mdiDeleteOutline,
    'mdi:desk': mdiDesk,
    'mdi:desk-lamp': mdiDeskLamp,
    'mdi:dip-switch': mdiDipSwitch,
    'mdi:door': mdiDoor,
    'mdi:door-closed': mdiDoorClosed,
    'mdi:door-closed-lock': mdiDoorClosedLock,
    'mdi:door-open': mdiDoorOpen,
    'mdi:door-sliding': mdiDoorSliding,
    'mdi:door-sliding-open': mdiDoorSlidingOpen,
    'mdi:doorbell': mdiDoorbell,
    'mdi:doorbell-video': mdiDoorbellVideo,
    'mdi:dots-grid': mdiDotsGrid,
    'mdi:dots-horizontal': mdiDotsHorizontal,
    'mdi:dots-vertical': mdiDotsVertical,
    'mdi:ev-plug-ccs1': mdiEvPlugCcs1,
    'mdi:ev-plug-ccs2': mdiEvPlugCcs2,
    'mdi:ev-plug-chademo': mdiEvPlugChademo,
    'mdi:ev-plug-type1': mdiEvPlugType1,
    'mdi:ev-plug-type2': mdiEvPlugType2,
    'mdi:ev-station': mdiEvStation,
    'mdi:eye': mdiEye,
    'mdi:eye-off': mdiEyeOff,
    'mdi:eye-off-outline': mdiEyeOffOutline,
    'mdi:eye-outline': mdiEyeOutline,
    'mdi:fan': mdiFan,
    'mdi:fan-off': mdiFanOff,
    'mdi:fan-speed-1': mdiFanSpeed1,
    'mdi:fan-speed-2': mdiFanSpeed2,
    'mdi:fan-speed-3': mdiFanSpeed3,
    'mdi:fast-forward': mdiFastForward,
    'mdi:file-export-outline': mdiFileExportOutline,
    'mdi:file-image-outline': mdiFileImageOutline,
    'mdi:file-import-outline': mdiFileImportOutline,
    'mdi:file-pdf-box': mdiFilePdfBox,
    'mdi:fire': mdiFire,
    'mdi:fire-off': mdiFireOff,
    'mdi:flash': mdiFlash,
    'mdi:flash-alert': mdiFlashAlert,
    'mdi:flash-alert-outline': mdiFlashAlertOutline,
    'mdi:flash-off': mdiFlashOff,
    'mdi:flashlight': mdiFlashlight,
    'mdi:flashlight-off': mdiFlashlightOff,
    'mdi:floor-lamp': mdiFloorLamp,
    'mdi:floor-lamp-outline': mdiFloorLampOutline,
    'mdi:folder-open-outline': mdiFolderOpenOutline,
    'mdi:folder-zip-outline': mdiFolderZipOutline,
    'mdi:garage': mdiGarage,
    'mdi:garage-alert': mdiGarageAlert,
    'mdi:garage-alert-variant': mdiGarageAlertVariant,
    'mdi:garage-open': mdiGarageOpen,
    'mdi:garage-variant': mdiGarageVariant,
    'mdi:garage-variant-lock': mdiGarageVariantLock,
    'mdi:gas-cylinder': mdiGasCylinder,
    'mdi:gas-station': mdiGasStation,
    'mdi:gate': mdiGate,
    'mdi:gate-open': mdiGateOpen,
    'mdi:gesture-double-tap': mdiGestureDoubleTap,
    'mdi:gesture-swipe-down': mdiGestureSwipeDown,
    'mdi:gesture-swipe-left': mdiGestureSwipeLeft,
    'mdi:gesture-swipe-right': mdiGestureSwipeRight,
    'mdi:gesture-swipe-up': mdiGestureSwipeUp,
    'mdi:gesture-tap': mdiGestureTap,
    'mdi:gesture-tap-hold': mdiGestureTapHold,
    'mdi:gesture-two-double-tap': mdiGestureTwoDoubleTap,
    'mdi:gesture-two-tap': mdiGestureTwoTap,
    'mdi:hand-wave': mdiHandWave,
    'mdi:heat-pump': mdiHeatPump,
    'mdi:heat-wave': mdiHeatWave,
    'mdi:help': mdiHelp,
    'mdi:help-circle': mdiHelpCircle,
    'mdi:help-circle-outline': mdiHelpCircleOutline,
    'mdi:home': mdiHome,
    'mdi:home-account': mdiHomeAccount,
    'mdi:home-alert': mdiHomeAlert,
    'mdi:home-alert-outline': mdiHomeAlertOutline,
    'mdi:home-analytics': mdiHomeAnalytics,
    'mdi:home-assistant': mdiHomeAssistant,
    'mdi:home-automation': mdiHomeAutomation,
    'mdi:home-city': mdiHomeCity,
    'mdi:home-export-outline': mdiHomeExportOutline,
    'mdi:home-flood': mdiHomeFlood,
    'mdi:home-floor-1': mdiHomeFloor1,
    'mdi:home-floor-2': mdiHomeFloor2,
    'mdi:home-floor-3': mdiHomeFloor3,
    'mdi:home-heart': mdiHomeHeart,
    'mdi:home-import-outline': mdiHomeImportOutline,
    'mdi:home-lightbulb': mdiHomeLightbulb,
    'mdi:home-lightbulb-outline': mdiHomeLightbulbOutline,
    'mdi:home-lightning-bolt': mdiHomeLightningBolt,
    'mdi:home-lightning-bolt-outline': mdiHomeLightningBoltOutline,
    'mdi:home-minus': mdiHomeMinus,
    'mdi:home-minus-outline': mdiHomeMinusOutline,
    'mdi:home-outline': mdiHomeOutline,
    'mdi:home-plus': mdiHomePlus,
    'mdi:home-plus-outline': mdiHomePlusOutline,
    'mdi:hvac': mdiHvac,
    'mdi:information': mdiInformation,
    'mdi:information-outline': mdiInformationOutline,
    'mdi:information-slab-box': mdiInformationSlabBox,
    'mdi:information-slab-circle': mdiInformationSlabCircle,
    'mdi:information-variant': mdiInformationVariant,
    'mdi:information-variant-box': mdiInformationVariantBox,
    'mdi:information-variant-circle': mdiInformationVariantCircle,
    'mdi:key': mdiKey,
    'mdi:key-alert': mdiKeyAlert,
    'mdi:key-alert-outline': mdiKeyAlertOutline,
    'mdi:key-outline': mdiKeyOutline,
    'mdi:key-variant': mdiKeyVariant,
    'mdi:key-wireless': mdiKeyWireless,
    'mdi:lamp': mdiLamp,
    'mdi:lamp-outline': mdiLampOutline,
    'mdi:lan': mdiLan,
    'mdi:lan-connect': mdiLanConnect,
    'mdi:lan-disconnect': mdiLanDisconnect,
    'mdi:lan-pending': mdiLanPending,
    'mdi:led-strip-variant': mdiLedStripVariant,
    'mdi:light-switch': mdiLightSwitch,
    'mdi:light-switch-off': mdiLightSwitchOff,
    'mdi:lightbulb': mdiLightbulb,
    'mdi:lightbulb-auto': mdiLightbulbAuto,
    'mdi:lightbulb-cfl': mdiLightbulbCfl,
    'mdi:lightbulb-cfl-off': mdiLightbulbCflOff,
    'mdi:lightbulb-fluorescent-tube': mdiLightbulbFluorescentTube,
    'mdi:lightbulb-group': mdiLightbulbGroup,
    'mdi:lightbulb-group-off': mdiLightbulbGroupOff,
    'mdi:lightbulb-group-off-outline': mdiLightbulbGroupOffOutline,
    'mdi:lightbulb-group-outline': mdiLightbulbGroupOutline,
    'mdi:lightbulb-off': mdiLightbulbOff,
    'mdi:lightbulb-off-outline': mdiLightbulbOffOutline,
    'mdi:lightbulb-on': mdiLightbulbOn,
    'mdi:lightbulb-on-outline': mdiLightbulbOnOutline,
    'mdi:lightbulb-outline': mdiLightbulbOutline,
    'mdi:lightning-bolt': mdiLightningBolt,
    'mdi:lightning-bolt-outline': mdiLightningBoltOutline,
    'mdi:link': mdiLink,
    'mdi:link-variant': mdiLinkVariant,
    'mdi:link-variant-off': mdiLinkVariantOff,
    'mdi:lock': mdiLock,
    'mdi:lock-alert': mdiLockAlert,
    'mdi:lock-alert-outline': mdiLockAlertOutline,
    'mdi:lock-open': mdiLockOpen,
    'mdi:lock-open-variant': mdiLockOpenVariant,
    'mdi:lock-open-variant-outline': mdiLockOpenVariantOutline,
    'mdi:lock-outline': mdiLockOutline,
    'mdi:lock-reset': mdiLockReset,
    'mdi:menu': mdiMenu,
    'mdi:menu-open': mdiMenuOpen,
    'mdi:minus': mdiMinus,
    'mdi:minus-circle': mdiMinusCircle,
    'mdi:minus-circle-outline': mdiMinusCircleOutline,
    'mdi:monitor': mdiMonitor,
    'mdi:monitor-off': mdiMonitorOff,
    'mdi:monitor-speaker': mdiMonitorSpeaker,
    'mdi:moon-waning-crescent': mdiMoonWaningCrescent,
    'mdi:motion-sensor': mdiMotionSensor,
    'mdi:motion-sensor-off': mdiMotionSensorOff,
    'mdi:music': mdiMusic,
    'mdi:music-box': mdiMusicBox,
    'mdi:music-box-outline': mdiMusicBoxOutline,
    'mdi:music-circle': mdiMusicCircle,
    'mdi:music-circle-outline': mdiMusicCircleOutline,
    'mdi:music-note': mdiMusicNote,
    'mdi:music-note-off': mdiMusicNoteOff,
    'mdi:music-off': mdiMusicOff,
    'mdi:open-in-new': mdiOpenInNew,
    'mdi:outdoor-lamp': mdiOutdoorLamp,
    'mdi:palette': mdiPalette,
    'mdi:palette-outline': mdiPaletteOutline,
    'mdi:pause': mdiPause,
    'mdi:phone': mdiPhone,
    'mdi:phone-alert': mdiPhoneAlert,
    'mdi:phone-hangup': mdiPhoneHangup,
    'mdi:phone-in-talk': mdiPhoneInTalk,
    'mdi:pipe': mdiPipe,
    'mdi:pipe-leak': mdiPipeLeak,
    'mdi:play': mdiPlay,
    'mdi:play-pause': mdiPlayPause,
    'mdi:playlist-check': mdiPlaylistCheck,
    'mdi:playlist-minus': mdiPlaylistMinus,
    'mdi:playlist-music': mdiPlaylistMusic,
    'mdi:playlist-play': mdiPlaylistPlay,
    'mdi:playlist-plus': mdiPlaylistPlus,
    'mdi:plus': mdiPlus,
    'mdi:plus-circle': mdiPlusCircle,
    'mdi:plus-circle-outline': mdiPlusCircleOutline,
    'mdi:pool': mdiPool,
    'mdi:power': mdiPower,
    'mdi:power-cycle': mdiPowerCycle,
    'mdi:power-off': mdiPowerOff,
    'mdi:power-on': mdiPowerOn,
    'mdi:power-plug': mdiPowerPlug,
    'mdi:power-plug-off': mdiPowerPlugOff,
    'mdi:power-plug-off-outline': mdiPowerPlugOffOutline,
    'mdi:power-plug-outline': mdiPowerPlugOutline,
    'mdi:power-settings': mdiPowerSettings,
    'mdi:power-sleep': mdiPowerSleep,
    'mdi:power-socket-eu': mdiPowerSocketEu,
    'mdi:power-socket-fr': mdiPowerSocketFr,
    'mdi:power-socket-uk': mdiPowerSocketUk,
    'mdi:power-socket-us': mdiPowerSocketUs,
    'mdi:power-standby': mdiPowerStandby,
    'mdi:progress-alert': mdiProgressAlert,
    'mdi:progress-check': mdiProgressCheck,
    'mdi:progress-clock': mdiProgressClock,
    'mdi:progress-close': mdiProgressClose,
    'mdi:progress-download': mdiProgressDownload,
    'mdi:progress-star': mdiProgressStar,
    'mdi:progress-upload': mdiProgressUpload,
    'mdi:progress-wrench': mdiProgressWrench,
    'mdi:projector': mdiProjector,
    'mdi:projector-screen': mdiProjectorScreen,
    'mdi:radar': mdiRadar,
    'mdi:radiator': mdiRadiator,
    'mdi:radiator-disabled': mdiRadiatorDisabled,
    'mdi:radiator-off': mdiRadiatorOff,
    'mdi:remote': mdiRemote,
    'mdi:remote-off': mdiRemoteOff,
    'mdi:remote-tv': mdiRemoteTv,
    'mdi:replay': mdiReplay,
    'mdi:restart': mdiRestart,
    'mdi:rewind': mdiRewind,
    'mdi:rocket': mdiRocket,
    'mdi:rocket-launch': mdiRocketLaunch,
    'mdi:rocket-launch-outline': mdiRocketLaunchOutline,
    'mdi:rocket-outline': mdiRocketOutline,
    'mdi:roller-shade': mdiRollerShade,
    'mdi:roller-shade-closed': mdiRollerShadeClosed,
    'mdi:router-network': mdiRouterNetwork,
    'mdi:router-wireless': mdiRouterWireless,
    'mdi:router-wireless-settings': mdiRouterWirelessSettings,
    'mdi:shield': mdiShield,
    'mdi:shield-home': mdiShieldHome,
    'mdi:shield-home-outline': mdiShieldHomeOutline,
    'mdi:shield-lock': mdiShieldLock,
    'mdi:shield-lock-outline': mdiShieldLockOutline,
    'mdi:shield-outline': mdiShieldOutline,
    'mdi:skip-next': mdiSkipNext,
    'mdi:skip-previous': mdiSkipPrevious,
    'mdi:smoke-detector': mdiSmokeDetector,
    'mdi:smoke-detector-alert': mdiSmokeDetectorAlert,
    'mdi:smoke-detector-outline': mdiSmokeDetectorOutline,
    'mdi:smoke-detector-variant': mdiSmokeDetectorVariant,
    'mdi:smoke-detector-variant-alert': mdiSmokeDetectorVariantAlert,
    'mdi:snowflake': mdiSnowflake,
    'mdi:snowflake-thermometer': mdiSnowflakeThermometer,
    'mdi:solar-panel': mdiSolarPanel,
    'mdi:solar-power': mdiSolarPower,
    'mdi:solar-power-variant': mdiSolarPowerVariant,
    'mdi:speaker': mdiSpeaker,
    'mdi:speaker-bluetooth': mdiSpeakerBluetooth,
    'mdi:speaker-multiple': mdiSpeakerMultiple,
    'mdi:speaker-off': mdiSpeakerOff,
    'mdi:speaker-wireless': mdiSpeakerWireless,
    'mdi:spotlight': mdiSpotlight,
    'mdi:spotlight-beam': mdiSpotlightBeam,
    'mdi:stop': mdiStop,
    'mdi:string-lights': mdiStringLights,
    'mdi:string-lights-off': mdiStringLightsOff,
    'mdi:sun-wireless': mdiSunWireless,
    'mdi:switch': mdiSwitch,
    'mdi:television': mdiTelevision,
    'mdi:television-ambient-light': mdiTelevisionAmbientLight,
    'mdi:television-classic': mdiTelevisionClassic,
    'mdi:television-off': mdiTelevisionOff,
    'mdi:theme-light-dark': mdiThemeLightDark,
    'mdi:thermometer': mdiThermometer,
    'mdi:thermometer-chevron-down': mdiThermometerChevronDown,
    'mdi:thermometer-chevron-up': mdiThermometerChevronUp,
    'mdi:thermometer-high': mdiThermometerHigh,
    'mdi:thermometer-lines': mdiThermometerLines,
    'mdi:thermometer-low': mdiThermometerLow,
    'mdi:thermostat': mdiThermostat,
    'mdi:timer': mdiTimer,
    'mdi:timer-off': mdiTimerOff,
    'mdi:timer-outline': mdiTimerOutline,
    'mdi:timer-sand': mdiTimerSand,
    'mdi:timer-sand-empty': mdiTimerSandEmpty,
    'mdi:toggle-switch': mdiToggleSwitch,
    'mdi:toggle-switch-off': mdiToggleSwitchOff,
    'mdi:toggle-switch-variant': mdiToggleSwitchVariant,
    'mdi:toggle-switch-variant-off': mdiToggleSwitchVariantOff,
    'mdi:transmission-tower': mdiTransmissionTower,
    'mdi:transmission-tower-export': mdiTransmissionTowerExport,
    'mdi:transmission-tower-import': mdiTransmissionTowerImport,
    'mdi:volume-high': mdiVolumeHigh,
    'mdi:volume-low': mdiVolumeLow,
    'mdi:volume-medium': mdiVolumeMedium,
    'mdi:volume-mute': mdiVolumeMute,
    'mdi:volume-off': mdiVolumeOff,
    'mdi:water': mdiWater,
    'mdi:water-off': mdiWaterOff,
    'mdi:water-outline': mdiWaterOutline,
    'mdi:water-percent': mdiWaterPercent,
    'mdi:water-pump': mdiWaterPump,
    'mdi:water-pump-off': mdiWaterPumpOff,
    'mdi:water-thermometer': mdiWaterThermometer,
    'mdi:water-well': mdiWaterWell,
    'mdi:weather-cloudy': mdiWeatherCloudy,
    'mdi:weather-fog': mdiWeatherFog,
    'mdi:weather-night': mdiWeatherNight,
    'mdi:weather-night-partly-cloudy': mdiWeatherNightPartlyCloudy,
    'mdi:weather-partly-cloudy': mdiWeatherPartlyCloudy,
    'mdi:weather-pouring': mdiWeatherPouring,
    'mdi:weather-rainy': mdiWeatherRainy,
    'mdi:weather-snowy': mdiWeatherSnowy,
    'mdi:weather-sunny': mdiWeatherSunny,
    'mdi:weather-sunny-alert': mdiWeatherSunnyAlert,
    'mdi:weather-sunset': mdiWeatherSunset,
    'mdi:weather-sunset-down': mdiWeatherSunsetDown,
    'mdi:weather-sunset-up': mdiWeatherSunsetUp,
    'mdi:weather-windy': mdiWeatherWindy,
    'mdi:weather-windy-variant': mdiWeatherWindyVariant,
    'mdi:webcam': mdiWebcam,
    'mdi:webcam-off': mdiWebcamOff,
    'mdi:wifi': mdiWifi,
    'mdi:wifi-off': mdiWifiOff,
    'mdi:wifi-strength-1': mdiWifiStrength1,
    'mdi:wifi-strength-2': mdiWifiStrength2,
    'mdi:wifi-strength-3': mdiWifiStrength3,
    'mdi:wifi-strength-4': mdiWifiStrength4,
    'mdi:wifi-strength-off': mdiWifiStrengthOff,
    'mdi:window-closed': mdiWindowClosed,
    'mdi:window-closed-variant': mdiWindowClosedVariant,
    'mdi:window-open': mdiWindowOpen,
    'mdi:window-shutter': mdiWindowShutter,
    'mdi:window-shutter-alert': mdiWindowShutterAlert,
    'mdi:window-shutter-open': mdiWindowShutterOpen,
};