import {
    mdiBackupRestore,
    mdiCheckBold,
    mdiChevronLeft,
    mdiChevronRight,
    mdiCloseCircleOutline,
    mdiCodeJson,
    mdiContentSave,
    mdiContentSavePlusOutline,
    mdiDeleteOutline,
    mdiEyeOffOutline,
    mdiEyeOutline,
    mdiFileExportOutline,
    mdiFileImageOutline,
    mdiFileImportOutline,
    mdiFilePdfBox,
    mdiFolderOpenOutline,
    mdiFolderZipOutline,
    mdiLinkVariant,
} from "@mdi/js";

export const MDI_UI_PATHS: Record<string, string> = {
    "mdi:backup-restore": mdiBackupRestore,
    "mdi:check-bold": mdiCheckBold,
    "mdi:chevron-left": mdiChevronLeft,
    "mdi:chevron-right": mdiChevronRight,
    "mdi:close-circle-outline": mdiCloseCircleOutline,
    "mdi:code-json": mdiCodeJson,
    "mdi:content-save": mdiContentSave,
    "mdi:content-save-plus-outline": mdiContentSavePlusOutline,
    "mdi:delete-outline": mdiDeleteOutline,
    "mdi:eye-outline": mdiEyeOutline,
    "mdi:eye-off-outline": mdiEyeOffOutline,
    "mdi:file-export-outline": mdiFileExportOutline,
    "mdi:file-image-outline": mdiFileImageOutline,
    "mdi:file-import-outline": mdiFileImportOutline,
    "mdi:file-pdf-box": mdiFilePdfBox,
    "mdi:folder-open-outline": mdiFolderOpenOutline,
    "mdi:folder-zip-outline": mdiFolderZipOutline,
    "mdi:link-variant": mdiLinkVariant,
};
